ephp_acl:
  access_log:
    enable: false
    class: \Ephp\ACLBundle\Entity\AccessLog
    check_ip: false
  user_class: \Ephp\ACLBundle\Entity\User
  facebook:
    app_id: 1234567890
    app_secret: 1234567890
    app_name: My Facebook App
    app_url: http://www.ephp.it
    app_description: This is my Facebook App
  
