# src/Acme/UserBundle/Resources/config/services.yml

parameters:
    my_user_provider.class: Ephp\ACLBundle\Security\Core\User\EphpUserProvider   
    #security.authentication.success_handler.class: SN\UserBundle\Security\Core\User\Configurazione

services:
    sn_user.registration.form.type:
        class: Ephp\ACLBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ephp_registration } # alias = nome form
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager, {facebook: facebookId, twitter: twitter_id}, @doctrine.orm.entity_manager, @router]
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
  
   # mio_servizio:
   #     class: SN\UserBundle\Security\Core\User\Configurazione
        #public: false
   #     arguments:  ['@router', '@security.user.entity_manager']        