<?php

namespace Ephp\ACLBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BaseAccessLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessLogRepository extends EntityRepository
{
}
