<?php

namespace Ephp\ACLBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BaseInvitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseInvitoRepository extends EntityRepository
{
}
